### PR TITLE
redesign of some glyphs for Shan

### PR DESCRIPTION
**Pull request by YusukeShirakihara**
Hello. Thank you for providing us with great fonts.
I’d like to submit a pull request regarding Noto Sans Myanmar for Shan language support.

About a year ago, SZTSIIT made the following issue https://github.com/notofonts/myanmar/issues/19 and pull request https://github.com/notofonts/myanmar/pull/63 about some incorrect characters, sizes and positioning of numbers for Shan in Noto Sans Myanmar.
Unfortunately, however, these topics were closed by SZTSIIT himself.

I’ve been working on fonts for Shan speaking people recently, and native speakers agreed with the changes in the request above.
Since the changes are desirable, I thought I might take over and submit this PR again.
In addition to SZTSIIT’s changes, we made a few adjustments.
And this PR is only for Noto **_Sans_** Myanmar.

**Sample**
ႁက္ႁည္ႁႁွႁုႁူႁႂႁ်ႂႁိုႁိူ
ၾက္ၾည္ၾၾွၾုၾူၾႂၾ်ႂၾိုၾိူ
ၽက္ၽည္ၽ
ꩡꩡ︀
႐႑႒႓႔႕႖႗႘႙
sample

Thank you for taking this request into consideration.

### CODE REVIEW

**Comment by simoncozens** [comment]
Hello Shirakihara-san! Thank you so much for this contribution. There are a few questions:

1. You will need to sign the CLA as mentioned above.
2. I may ask someone to review the design; in my view the subscript FA looks quite squashed. I think probably all the glyphs want to keep the basic "circular" form.
3. I am not sure if we really want smaller versions of subscripts underneath NNYA. I think we can probably fit full size subscripts there?

**Comment by YusukeShirakihara** [comment]
@simoncozens Thank you for your quick reply. Here are answers to each of your comments.

> 1. You will need to sign the CLA as mentioned above.

I have signed the CLA and rescanned this request, but it has not been reflected... is there anything I can do?

> 2. I may ask someone to review the design; in my view the subscript FA looks quite squashed. I think probably all the glyphs want to keep the basic "circular" form.

I agree with you. I updated fa_shn.sub and fa_shn.sub2. Could you check again?
sample-Regular
> 3. I am not sure if we really want smaller versions of subscripts underneath NNYA. I think we can probably fit full size subscripts there?

That could be true, but it’s fine the way it is in Black. I think it would be better to adjust “blws” in the features.
sample-Black

**Comment by berrymot** [comment]
why is the subscript on က္ႁ a different size from the one on ည္ႁ? (even in whichever version my iphone has currently)

**Comment by simoncozens** [comment]
> I have signed the CLA and rescanned this request, but it has not been reflected... is there anything I can do?

I've worked out what is happening here; because you are using GitHub's "Keep my email address private" setting, you must change the email address in your CLA to your GitHub email (`122098208+YusukeShirakihara​@users.noreply.github.com`)

**Comment by YusukeShirakihara** [comment]
I see. I unchecked that setting.

**Comment by YusukeShirakihara** [comment]
> why is the subscript on က္ႁ a different size from the one on ည္ႁ? (even in whichever version my iphone has currently)

As you pointed out, in regular weight, both can be the same size, but in bolder weight such as black, the subscript ္ႁ seems too big for ည. I'm not sure, but that's may be the reason why Noto Sans Myanmar fonts are designed this way.

**Comment by berrymot** [comment]
the sizes are different even in regular, per the image above
image

**Comment by YusukeShirakihara** [comment]
Sorry, my answer might have been a little confusing. Yes, in the current Regular design, the sizes are different. What I meant was that while it might be possible to make them the same size in Regular, it is probably difficult in bolder weights. But there may be other solution to this. It could be helpful if someone who knows about this font or the Shan language better provide us with further information on this.

**Comment by berrymot** [comment]
ahh okay yes. I feel like maybe consistent height & squishing them horizontally if needed could work

**Comment by YusukeShirakihara** [comment]
This request is closed for now.

**Pull request closed without merging**
